### ISSUE TITLE
Table nested in numbered list breaks the sequence in preview pane.

### ISSUE THREAD

**Issue by gomezrjo** [MacDownApp/macdown#1189] opened 2020-05-25 16:50 UTC
The following sample text renders incorrectly in the preview pane:

>1. Item 1
>2. Item 2
>
>Field | Value
>------|-------
>field 1 | value 1
>field 2 | value 2
>
>3. Item 3

Item 3 shows as number 1 again in preview pane. 

The good news is that when I publish to github it renders as expected with "Item 3" using number 3. 

However, from time to time I need to export the document as PDF and the rendering shows the wrong numbering.

**Comment by FranklinYu** [comment] 2020-06-22 05:16
Duplicate of #1049

**Closed by FranklinYu** 2020-06-22 05:16 UTC
