### ISSUE TITLE
Using `macdown` to open existing file from shell results in empty window

### ISSUE THREAD

**Issue by mikeokner** [MacDownApp/macdown#602] opened 2016-04-20 16:38 UTC
Installed with homebrew `brew cask install macdown` which pulled v0.6. Mac OS X 10.11.3 El Capitan.

- If I double click a `.md` file or open it with File > Open within `MacDown.app` then it works fine and loads the contents of the file.
- If I open a file using `macdown filename.md` on a shell and `MacDown.app` is already running it works fine and loads the contents of the file.
- If I open a file using `macdown filename.md` and `MacDown.app` isn't already running, it opens an empty window with the dot in the close box indicating there are unsaved edits. When I close the window without making any edits of my own, it asks me if I want to save the changes made to `filename.md`.

**Comment by ryanmcgrath** [comment] 2016-04-21 09:49
Gonna just tag onto this issue and note that Macdown also crashes completely for me if I open a new file from the shell and go to save it.

This is completely annoying as I just lost a significant amount of work.

**Comment by uranusjr** [comment] 2016-04-27 06:26
Seems that some tricks I used to was broken by the latest OS X update. Thanks for reporting.

**Comment by Jmuccigr** [comment] 2016-04-27 12:29
Meanwhile if you have the binary installed from the website, it'll check for updates and you can always do something like:

`alias macdown='open -a MacDown.app'`

will give you the CLI functionality you had with the brew install.

**Comment by franklinyu** [comment] 2016-10-09 00:32
This seems to be a duplicate of #612 and should now be fixed in [v0.6.2](https://github.com/MacDownApp/macdown/releases/tag/v0.6.2). Guys, would you like to confirm it?

**Closed** 2016-10-09 03:23 UTC
Labels: duplicate
