### ISSUE TITLE
Software update fails

### ISSUE THREAD

**Issue by kneden** [MacDownApp/macdown#1119] opened 2019-12-03 19:08 UTC
Tried to install the 0.7.2 update via software update feature and it failed. This was with version 0.7.1 on macOS 10.14.6.

After MacDown downloads and extracts the update, I clicked the "Install and Relaunch" button and then an "Update Error!" dialog is displayed:

![MacDownUpdateFailed](https://user-images.githubusercontent.com/17029374/70079537-f1aa3280-15d2-11ea-8598-ac73d90af680.png)

Here are some logs from Console that appeared just after clicked "Install and Relaunch" that I think are relevant:
```
default	13:35:01.811452 -0500	MacDown	CSSM Exception: -2147415792 CSSMERR_CSP_INVALID_KEY
default	13:35:01.837421 -0500	securityd	CSSM Exception: -2147415734 CSSMERR_CSP_VERIFY_FAILED
default	13:35:01.838210 -0500	securityd	CSSM Exception: -2147415734 CSSMERR_CSP_VERIFY_FAILED
default	13:35:01.838704 -0500	MacDown	CSSM Exception: -2147415734 CSSMERR_CSP_VERIFY_FAILED
```

I suspect it has something to do with the signing of the update.

```
$ spctl --assess ~/Library/Caches/com.uranusjr.macdown/Sparkle/MacDown\ 1008/MacDown.app
/Users/kneden/Library/Caches/com.uranusjr.macdown/Sparkle/MacDown 1008/MacDown.app: a sealed resource is missing or invalid
```

**Comment by lefte** [comment] 2019-12-03 21:27
I went a step further, and attempted to reinstall the Homebrew version of 0.7.2, and now, all I get is: 

> "MacDown.app" is damaged and can't be opened. You should move it to the Trash. 😢

![image](https://user-images.githubusercontent.com/1946808/70091238-566c8980-15e1-11ea-8f8f-1ed0659b0eb4.png)

**Comment by lefte** [comment] 2019-12-03 21:35
**Update.** After searching other issues in this repo, I discovered a fix for reinstalling:
`sudo xattr -r -d com.apple.quarantine /Applications/MacDown.app/` which removes the Apple quarantine on MacDown, letting it open. Good luck!

**Comment by FranklinYu** [comment] 2019-12-03 23:09
Duplicate of #1106

**Closed by FranklinYu** 2019-12-03 23:09 UTC
