### ISSUE TITLE
code block is not wrapped when exporting PDF

### ISSUE THREAD

**Issue by breezepqf** [MacDownApp/macdown#972] opened 2018-05-02 15:45 UTC
When l try to export PDF.
IF l turn  on the function of  syntax highlighted code block 

the code block of PDF shows like this 

<img width="1057" alt="screen shot 2018-05-02 at 11 30 22 pm" src="https://user-images.githubusercontent.com/25058314/39534204-a56f9fb4-4e63-11e8-8aed-aa8e0174cb25.png">
if l use the plain mode, it works fine and the code block will wrapping lines automatically.

<img width="1069" alt="screen shot 2018-05-02 at 11 29 42 pm" src="https://user-images.githubusercontent.com/25058314/39534203-a50b7840-4e63-11e8-83a8-fa3b23254985.png">

So l guess many customers will not find this issue can be solved by this way. And l suppose that you guys should fix it or at lease let us know how to solve similar problems.

**Comment by franklinyu** [comment] 2018-05-02 17:50
Duplicate of #483

**Closed by franklinyu** 2018-05-02 17:50 UTC

**Comment by ortonomy** [comment] 2020-01-26 02:34
This was marked as duplicated, but the original has not been touched for 5 years! Any chance of actually doing something about this?!?!

**Comment by FranklinYu** [comment] 2020-01-26 09:31
I assume by “not touched” you meant “not resolved”. There are comments from time to time. Claiming it “not being touched” is kind of misleading…

This is not my priority (there are so many more issues out there). PR is always welcome.

**Comment by nexus9111** [comment] 2025-01-08 12:54
still not fixed ?
