### ISSUE TITLE
Exported PDFs don't include a table of contents

### ISSUE THREAD

**Issue by manuelciosici** [MacDownApp/macdown#792] opened 2017-04-20 14:11 UTC
By its nature, MarkDown includes semantic annotations for document structure (i.e. headings). The exported PDFs should include a PDF table of contents.

To be clear, I am not talking here about a page containing a table of contents, but I am talking about having a table of contents directly in the PDF file that PDF readers can utilize to allow users to jump directly to specific sections of a document.

**Comment by franklinyu** [comment] 2017-04-20 18:30
Duplicate of #782.

**Closed by franklinyu** 2017-04-20 18:30 UTC

**Comment by Hipska** [comment] 2017-11-06 14:23
You see, that's why I suggested to keep 1 issue about ToC open, so nobody will create new ones again ;-)
