### ISSUE TITLE
Preview pane  and Preferences pane is empty?

### ISSUE THREAD

**Issue by xavierskip** [MacDownApp/macdown#341] opened 2015-04-10 12:34 UTC
I use this tools to edit my blog post .but like this  http://ww1.sinaimg.cn/large/6afb06cdgw1er0qmsrakbj20ss0h0gpl.jpg

The more strange is  when I first open the file things go wrong but close the file and reopen it everything right!? (sometimes still malfunction)

what the hell?

my post file you can find there https://github.com/xavierskip/xavierskip.github.com/tree/master/_posts
and my system is OS X 10.9.5

**Comment by NickVolynkin** [comment] 2015-05-27 07:30
Almost the same in my case.
### What happens

- MacDown doesn't open any files from Finder (doesn't show editor window)
- Preferences panes are all empty
- Preview pane doesn't update
- Consequent reopening the same file doesn't help (not as in xavierskip's case)

### What I did before a crash
I changed some settings regarding the markdown rendering. Shortly after that MacDown first refused to open a document.
I also tried to completely reinstall MacDown (also deleted files in /Library/...), but it gives no effect.

**Comment by NickVolynkin** [comment] 2015-05-27 07:50
Fixed!
### How to fix this problem.
<ol> <li> Move the following files to trash: </li>
```
/Users/<your_name>/Library/Preferences/com.uranusjr.macdown.LSSharedFileList.plist  
/Users/<your_name>/Library/Preferences/com.uranusjr.macdown.plist  
```
<li>Empty the trash.</li>
If you receive a message that files are busy and cannot be deleted, reboot your OS. Then empty the trash again.

**Comment by uranusjr** [comment] 2015-05-27 08:04
The solution looks right to me. The two files are definitely what holds the preferences. But the bug should not happen in the first place. Could you share your preference settings when it happens? It might help if you could upload the files somewhere before you delete them, so I can take a look at their contents.

**Comment by NickVolynkin** [comment] 2015-05-27 08:15
Okay, I shall try to reproduce the bug.

**Comment by NickVolynkin** [comment] 2015-07-11 03:43
Reproduced the issue with these configs: https://github.com/NickVolynkin/markdown-issue-341

**Comment by NickVolynkin** [comment] 2015-07-16 04:58
Reproduced again. The new configs are in the same repo, next commit. MacDown version 0.4.5.1

**Comment by uranusjr** [comment] 2015-07-16 08:11
@NickVolynkin Just to make sure: Are you opening `КА Сухорукова, Анна Панькова/test.md` in both cases?

I think I know the problem: from the system seems to consider your preview pane hidden (and thus not updating it), but in reality it really is visible. I don’t yet know why this happens, but now I know where to look.

**Comment by NickVolynkin** [comment] 2015-07-16 08:30
[First time][1] it crashed on a different file, but the second and third — on the one that you've mentioned. It contains indented code blocks, inline code, numbered and bulleted lists, links, citations and headers. Those are almost all markdown features.

Looks like I've localized the problem. It happens when I toggle these options:
<img width="293" alt="screen shot 2015-07-16 at 14 17 02" src="https://cloud.githubusercontent.com/assets/8015154/8718323/14d79a4a-2bbd-11e5-889c-19bfe547c863.png">

They're off by default. 

1. Switch on [ x ] the first checkbox
2. Switch on [ x ] the first checkbox
3. Now the  source doesn't render anymore. (at least on my machine, with fresh configs)
4. Switch off [  ] the first checkbox
5. Source renders again.
6. Switch on [ x ] the first checkbox.
7. Now source doesn't render again.
8. The config pane doesn't render too. It shows the [x] on first option, but the second stays shaded (disabled)
9. Toggle to any other tab of config pane.
10. This tab is empty.

 [1]: https://github.com/uranusjr/macdown/issues/341#issuecomment-105798653

**Comment by uranusjr** [comment] 2015-07-16 10:19
I’ll first try to reproduce this without the original file.

The line number thing is another problem—I just did some tests and it seems like it only works if you supply a valid language name. So line numbers show for this:

    ~~~bash
    cd /etc
    ls
    ~~~

But not this:

    ~~~
    cd /etc
    ls
    ~~~

I’ll also look into fixing that.

**Comment by NickVolynkin** [comment] 2015-07-16 12:14
I didn't use the `~~~` notation at all. Just the four spaces indentation.

**Comment by NickVolynkin** [comment] 2015-08-23 18:28
Since #410 is resolved, I could not reproduce this bug with the same steps. The issue should probably be closed.

**Comment by franklinyu** [comment] 2016-08-24 00:47
Closing this. Comment to reopen this issue if necessary.

**Closed by franklinyu** 2016-08-24 00:47 UTC
Labels: bug
