### ISSUE TITLE
"Find Again" doesn't work

### ISSUE THREAD

**Issue by kkdd** [MacDownApp/macdown#875] opened 2017-10-25 14:55 UTC
Hello,
I have found that "Find Again" doesn't work after typing characters into the search form but after "Enter Selection". (MacDown 0.7.1, macOSX 10.11.6)

**Comment by Jmuccigr** [comment] 2017-10-29 18:37
Duplicate of #343?

**Comment by franklinyu** [comment] 2017-10-30 03:15
@Jmuccigr Probably. @kkdd please comment if it's not.

**Closed by franklinyu** 2017-10-30 03:15 UTC
