### ISSUE TITLE
Links to anchor don't work on pdf

### ISSUE THREAD

**Issue by gsanchezd** [MacDownApp/macdown#503] opened 2015-11-18 22:02 UTC
Using links tu anchors including the ones generated by the [TOC] don't work on the PDF.

**Comment by LoveDaisy** [comment] 2018-07-09 03:09
I've met the same problem.
I notice that @gsanchezd met this problem when 2015. And this issue is still open. I'm not sure is there any solution or workaround now?

**Comment by franklinyu** [comment] 2018-07-24 14:22
Duplicate of #198

**Closed** 2018-07-24 14:22 UTC
