### ISSUE TITLE
Preview pane desynchronized from editor when using Base64 encoded inline images

### ISSUE THREAD

**Issue by dbarowy** [MacDownApp/macdown#854] opened 2017-09-20 20:37 UTC
Inserting a Base64 encoded image (ala `[img]: data:image/png;base64,...`) causes the preview pane to become desynchronized from the editor pane when scrolling in the editor.  This is annoying, to say the least.

If this is unclear, let me know and I will supply a minimal working Markdown file to demonstrate.

**Comment by uranusjr** [comment] 2017-09-21 03:00
I know what you’re talking about, and this is indeed annoying. It has its roots deep inside our currently rendering system, and can’t be fixed without a big overhaul unfortunately.

**Comment by franklinyu** [comment] 2017-09-21 13:53
Marking this as bug, because this is what we are trying to do well (although it's difficult to).

**Comment by adamwulf** [comment] 2018-03-27 06:06
This should be fixed now from #933

**Closed** 2018-04-19 14:14 UTC
Labels: bug

**Comment by champagnealexandre** [comment] 2019-05-25 00:28
Using MacDown Version 0.7.1 (870) - doesn't look like it's fixed (I was about to open up an issue for this).

Are you able to reproduce the problem? If not, I can provide a MWE.
