### ISSUE TITLE
Flashing preview while writing after update to Version 0.7.3 (1008.4)

### ISSUE THREAD

**Issue by undavide** [MacDownApp/macdown#1160] opened 2020-02-29 15:00 UTC
Hi,

ever since I've updated to 0.7.3 (1008.4), the Preview keeps flashing while I type in the Editor. Flashing means that it goes solid black for an annoying fraction of a second then the content is displayed as usual; it happens around each 1-3 seconds, depending on how fast I type. 

I'm on macOS 10.14.6 (18G2022) and I don't remember to have seen this behaviour in the past. Is it possible to downgrade until the issue is fixed? Thanks!

Davide

**Comment by undavide** [comment] 2020-02-29 16:54
Uhm, I've to correct myself – I've downloaded v.0.7.2 and it still flashes, I'll report back if I find anything relevant to add...

**Comment by FranklinYu** [comment] 2020-03-01 08:48
Duplicate of #1104

**Closed by FranklinYu** 2020-03-01 08:48 UTC
