### ISSUE TITLE
Sidebar and tabbed interface

### ISSUE THREAD

**Issue by trapias** [MacDownApp/macdown#603] opened 2016-04-22 07:27 UTC
Feature request: what about adding...
- a sidebar to browse folders & files
- a tabbed interface, so to easily manage multiple open files 

I believe this would greatly improve usability. For example http://lightpaper.42squares.in has both 😄

**Comment by franklinyu** [comment] 2016-08-24 21:11
For the tab interface, try macOS Sierra, as described in #617.

**Comment by kenbailey** [comment] 2017-02-17 16:22
The tabbed interface #617 works great. Any chance we can have an option to open new windows via links in the Preview on the tab (rather than opening a separate window).  If this isn't desired default behavior, possibly extending the right click to "Open in tab...".

Great work on the app!

**Comment by franklinyu** [comment] 2017-02-17 18:43
@kenbailey Interesting idea. That deserves a stand-alone issue!

**Comment by kenbailey** [comment] 2017-02-17 18:58
I'll create a new issue for it then.

**Comment by franklinyu** [comment] 2017-02-17 19:27
Closing this issue though. The tab part is duplicate of #631, so if anyone has any issue, please report at #631. The sidebar part is duplicate of #141.

**Closed by franklinyu** 2017-02-17 19:27 UTC
Labels: enhancement
