### ISSUE TITLE
preview pane jumps and flickers in v0.7.2

### ISSUE THREAD

**Issue by cdimascio** [MacDownApp/macdown#1118] opened 2019-12-01 20:55 UTC
in v0.7.2, on each keystroke, the preview pane is refreshed,  but the refresh itself displays an odd behavior. the refresh seems to cause the preview to briefly jump to the top of the document, then back to the section being edited. it leads to a flicker and makes it easy to lose your place

**Comment by FranklinYu** [comment] 2019-12-02 00:12
Duplicate of #1104

**Closed by FranklinYu** 2019-12-02 00:12 UTC
