### ISSUE TITLE
Refresh image rendering when changed in the finder

### ISSUE THREAD

**Issue by Mini-Stef** [MacDownApp/macdown#622] opened 2016-06-19 07:56 UTC
If a picture is rendered on the right pane, then changing the image file directly in the finder has no effect on the rendering. I found no other way than to close/re-open the md file. It would be nice to have at least a "reload image" option somewhere.

**Comment by franklinyu** [comment] 2016-07-30 21:10
How about right-click on the webpage, then select "reload"?

**Comment by hopscotch** [comment] 2016-10-05 18:54
right-click `reload` has issues ...

## Setup

_Raster Image_  
```markdown
![alt text](image.png "Raster Image")
```
_Vector Image_  
```markdown  
![alt text](image.svg "Vector")
```

## Steps

STEP 1: Edit image.png and image.svg in an external editor.

_Observation 1: MacDown does not detect the file change._

STEP 2: Reload Preview via Right-Click

_Observation 2: MacDown Preview only shows the **raw source text** and does not re-render images._

[click here for step 2 result](https://cloud.githubusercontent.com/assets/1441610/19126817/530bc0d6-8af1-11e6-9db6-6f248a6241d7.png)

STEP 2: Edit this source in Editor Pane.

_Observation 3: An Editor Pane change will cause a re-render. **However, the re-render shows as some cached version and does not update to the current image files.**_ 

[click here for step 3 result](https://cloud.githubusercontent.com/assets/1441610/19126818/530c2864-8af1-11e6-8d64-1e744665889c.png)

After multiple edit, image.png updates but image.svg remains unchanged without a quit and restart of the MacDown application.
 
## Expected Behavior

1. `Reload` was expected to re-render the images rather than just dumping the source file.
2. `Reload` was expected to not require a change in the Edit Pane to trigger a re-render.
3. `Reload` was expected to reload from the changed source and not some unchanged (cached?) version.  
4. `Reload` was expected to be easily found on some place like on the application menubar with key equivalent in addition to the context menu.

## Possible Enhancements

1. Add `Show Source` to the `Reload` right-click context menu item.
2. Add `Reload` to the top application menubar.
3. Auto detection of image file changes would be a great enhancement.

## Related Issue

[#606 Open SVG Source > Edit Source > Export SVG > Reload ... fails.](https://github.com/MacDownApp/macdown/issues/606)  

## Uploaded Files

Remove `.txt` from `image.svg.txt` and `MacDownImageRefreshTest.md.txt` to have the example test file set.

[MacDownImageRefreshTest.md.txt](https://github.com/MacDownApp/macdown/files/512061/MacDownImageRefreshTest.md.txt)
[image.svg.txt](https://github.com/MacDownApp/macdown/files/512064/image.svg.txt)

![image](https://cloud.githubusercontent.com/assets/1441610/19126819/530dc37c-8af1-11e6-9bb5-547e78ea31e3.png)
![result_step2](https://cloud.githubusercontent.com/assets/1441610/19126817/530bc0d6-8af1-11e6-9db6-6f248a6241d7.png)
![result_step3](https://cloud.githubusercontent.com/assets/1441610/19126818/530c2864-8af1-11e6-8d64-1e744665889c.png)

**Comment by Mini-Stef** [comment] 2016-10-05 20:10
@franklinyu First of all, sorry for being soooo long to answer you. I have missed your post.

Second, I can confirm everything related in hopscotch's post. Definitely, the reload is not an option.
TO me, the only way forward is "Auto detection of image file changes would be a great enhancement.
"

**Comment by franklinyu** [comment] 2016-10-06 03:35
I can reproduce similar bug, but the behavior on my machine seems a little bit different. I can reproduce *Observation 1* with *Step 1*; when I do *Step 2*, it does not give me the source Markdown, but simply freezes. I cannot scroll up or down. If I then *Render Markdown* (in menu or with <kbd>⌘</kbd> + <kbd>R</kbd>) it recovers with the cached image, then I can do *Step 3* and reproduce *Observation 3*. So yes, I can confirm the bug.

If the system hook of file update is found, I guess we can solve the bug. I notice that #651 is using the same thing (file system hook) to implement another feature, but it does not progress well, sadly.

**Comment by hopscotch** [comment] 2016-10-06 07:53
I think that there are two levels of fix to consider.  The 2nd level could build on a 1st level solution.

Level 1. Manual. Have the manual `Reload` and `Render Markdown` start with the source (non-cached) image files to regenerate the internal html and then subsequently render the html.  Level 1 should not require file change event hooks.

Level 2. Automated. Monitor the linked image files to automate the calling of a working `Reload` or `Render Markdown` as described in level 1.  Level2 would need a [File System Events](https://developer.apple.com/library/prerelease/content/documentation/Darwin/Conceptual/FSEvents_ProgGuide/Introduction/Introduction.html) or [Kernel Queue](https://developer.apple.com/library/prerelease/content/documentation/Darwin/Conceptual/FSEvents_ProgGuide/KernelQueues/KernelQueues.html) or some file change monitor. … and might need to be reworked with the future Apple File System (APFS).

In my case, I would be happy with Level 1 sooner. Then, Level 2 later when particulars of file change hooks are figured out and implemented.

**Comment by franklinyu** [comment] 2016-10-06 16:18
Agree. The two-level strategy probably also applies to #651.

cc @uranusjr.

**Comment by franklinyu** [comment] 2016-10-06 18:43
Is this a duplicate of #222?

**Comment by Mini-Stef** [comment] 2016-10-06 19:03
Yes, seems like a duplicate.

**Closed** 2016-11-04 10:59 UTC
Labels: bug, duplicate
