### ISSUE TITLE
Highlight trailing spaces

### ISSUE THREAD

**Issue by jenstroeger** [MacDownApp/macdown#819] opened 2017-06-13 07:19 UTC
Considering the [significance of trailing spaces for list items](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists) in Markdown, it would help a lot to show them in MacDown’s editor. Just a [Unicode bullet](http://www.fileformat.info/info/unicode/char/2022/index.htm) character would suffice.

**Comment by franklinyu** [comment] 2017-06-13 15:31
Duplicate of #613. Also note that trailing space affect all paragraph blocks, not just the one in lists. For example

```markdown
foo⋅⋅
bar
```

is rendered (in CommonMark) as

> foo
> bar

**Closed by franklinyu** 2017-06-13 15:31 UTC
