### ISSUE TITLE
Command-Shift-B breaks MacDown until restart.

### ISSUE THREAD

**Issue by neon64** [MacDownApp/macdown#568] opened 2016-02-20 01:56 UTC
Sometimes when i press Command-Shift-B to create a blockquote the cursor disappears/stops blinking and I can't type anything, or save the document, or use any keyboard shortcuts. Additionally, when I open new windows/existing documents they just open up to a black window without a title bar.

This can only be fixed by restarting Macdown itself. ie: I can't just reopen the window.

This appears to happen most often after an unordered list using the `-` character. If I press enter twice and then Command-Shift-B it will break.

Here are some screenshots:

![screen shot 2016-02-20 at 12 52 15 pm](https://cloud.githubusercontent.com/assets/7961339/13193704/4b0d738a-d7d1-11e5-89f4-ff0e673c4c8a.png)

Here everything looks normal but I cannot type anything/move the cursor.

![screen shot 2016-02-20 at 12 52 35 pm](https://cloud.githubusercontent.com/assets/7961339/13193705/4d454826-d7d1-11e5-928d-48f06f48d48d.png)

Trying to open a new window.

This seems similar to https://github.com/uranusjr/macdown/issues/546 but I'm not sure.

**Comment by getaaron** [comment] 2016-02-22 01:49
@neon64 Thanks for the bug report. Have you had a chance to reproduce through Xcode? Have you investigated the cause at all?

**Comment by neon64** [comment] 2016-02-23 08:57
No, I haven't looked at it in Xcode at all (the Xcode window in the background was just an unrelated project). Should I just clone the repo, open the Xcode project, run it and set breakpoints/look at the debugger? I haven't looked at all at the source of MacDown so I probably don't know where to start.

**Comment by uranusjr** [comment] 2016-02-27 05:27
This might be related to 87f7755. The block syntax toggle could underflow in various cases, but it should not crash the app under normal circumstances (OS X catches it). But maybe.

**Comment by uranusjr** [comment] 2016-03-17 22:49
Closing as fixed unless there are more reports on this.

**Closed by uranusjr** 2016-03-17 22:49 UTC
