### ISSUE TITLE
An editor syntax color bug!

### ISSUE THREAD

**Issue by GitHub27182818** [MacDownApp/macdown#995] opened 2018-07-01 12:42 UTC
<img width="1673" alt="screen shot 2018-07-01 at 20 40 43" src="https://user-images.githubusercontent.com/15006150/42134486-3a4a690e-7d6f-11e8-8b5b-a42b6e812ab2.png">

**Comment by GitHub27182818** [comment] 2018-07-01 12:49
<img width="1673" alt="screen shot 2018-07-01 at 20 48 49" src="https://user-images.githubusercontent.com/15006150/42134532-339431fc-7d70-11e8-94a6-e3555ebf01aa.png">

**Comment by franklinyu** [comment] 2018-07-05 13:45
Duplicate of #489

**Closed** 2018-07-05 13:46 UTC
