### ISSUE TITLE
Feature: Add side panel for opened folder

### ISSUE THREAD

**Issue by lolgear** [MacDownApp/macdown#856] opened 2017-09-26 08:54 UTC
It would be nice to have two features ( or one ? )

- Open folder in MacDown
- Opened folder content appears on the side panel.

( Like Sublime text 3 does ).

**Comment by franklinyu** [comment] 2017-09-26 14:25
Possibly duplicate of #141.

**Closed by franklinyu** 2017-09-26 14:25 UTC
