### ISSUE TITLE
What does the `$` character do?

### ISSUE THREAD

**Issue by GiannisGG** [MacDownApp/macdown#902] opened 2017-12-21 16:04 UTC
I have a question in regard to the `$` symbol. What is its effect in MacDown? Or in markdown in general? I don't seem to find an answer by googling about it.

Writing two `$`, turns everything in between into dark grey text. Moreover- **the headings disappear** (they still exist as headings when I export, but they are not clearly visible in the MacDown editor.)

For example, try pasting this into MacDown:

```
It costs $9,000.

### Jewelry business

If someone puts his $30K diamond into a ring or a necklace...
```

The ### heading shows no different to the rest of the greyed out text.

Can I deactivate whatever effect the `$` has and keep it as the simple dollar symbol?

Thanks!
G.

**Comment by franklinyu** [comment] 2017-12-21 16:40
The syntax highlight has some bug, but the preview should work. Doesn't it?

**Comment by nanoguo** [comment] 2017-12-22 02:43
@franklinyu the preview works well.
![image](https://user-images.githubusercontent.com/25052775/34283069-aefc6fd8-e704-11e7-9668-ad5ce2b4b99b.png)

**Comment by franklinyu** [comment] 2017-12-22 16:19
Duplicate of #489.

**Closed by franklinyu** 2017-12-22 16:19 UTC
