### ISSUE TITLE
[Enhancement] Project/Folder view

### ISSUE THREAD

**Issue by debradley** [MacDownApp/macdown#776] opened 2017-03-23 13:43 UTC
It'd be nice to be able to open a folder, which would then create a treeview pane on the left showing all markdown files in that folder and its children, as in Sublime, Atom, et al. Any files selected in the treeview pane would automatically open in a tab within the current window.

**Comment by franklinyu** [comment] 2017-03-23 14:01
Please reopen if it isn't a duplicate of #141.

**Closed by franklinyu** 2017-03-23 14:01 UTC
