### ISSUE TITLE
[feature]auto merge windows in MACOS 10.12

### ISSUE THREAD

**Issue by jinleileiking** [MacDownApp/macdown#679] opened 2016-10-19 03:10 UTC

**Comment by franklinyu** [comment] 2016-10-19 21:54
So it doesn't work for you? This is weird, since it is reported as working in #617. Just to make sure, both your MacDown and macOS are up to date, right?

**Comment by jinleileiking** [comment] 2016-10-20 07:48
macdown
Version 0.6.2 (772)

macos: sirria

**Comment by franklinyu** [comment] 2017-02-17 18:39
Duplicate of #631.

**Closed by franklinyu** 2017-02-17 18:39 UTC
Labels: help wanted
