### ISSUE TITLE
Release 0.7.2 causes flicker

### ISSUE THREAD

**Issue by massenz** [MacDownApp/macdown#1124] opened 2019-12-10 14:24 UTC
I have just installed `Version 0.7.2 (1008)` on my MacBook (Catalina, 10.15.1) and it is nearly unusable due to the constant flickering, after each keystroke.

I have re-installed the previous version, and it is much more "stable" in that it does not refresh nearly as aggressively.

Toolbar support is (kinda) nice, but as it is, this release is not very usable.

**Comment by FranklinYu** [comment] 2019-12-11 07:27
Duplicate of #1104

**Closed by FranklinYu** 2019-12-11 07:27 UTC
