### ISSUE TITLE
No options showing in markdown preferences pane on Mojava

### ISSUE THREAD

**Issue by rwhit** [MacDownApp/macdown#1128] opened 2019-12-19 14:14 UTC
OSX 10.14.6, headers ("Document formatting", etc.) showing on the Markdown Preferences pane, but no options. Screenshot attached.
![Screen Shot 2019-12-19 at 9 13 07 AM](https://user-images.githubusercontent.com/270713/71180290-daf51400-223f-11ea-9a35-551c2779ab34.png)

**Comment by fadookie** [comment] 2019-12-19 17:41
I am also seeing this after updating to MacDown version 0.7.2.

I am running macOS 10.14.6.

**Comment by FranklinYu** [comment] 2019-12-20 21:37
Duplicate of #1103

**Closed by FranklinYu** 2019-12-20 21:37 UTC
