### ISSUE TITLE
Long lines breaks in code block PDF output

### ISSUE THREAD

**Issue by palkoc** [MacDownApp/macdown#861] opened 2017-10-02 15:32 UTC
## Hi all,
is there any way how to automatically break long lines in code block PDF output?
### Example in editor:
![screen shot 2017-10-02 at 17 28 37](https://user-images.githubusercontent.com/6809559/31085410-50b065f8-a797-11e7-83bf-b80d8f1f5503.png)

### And this is the output:

![screen shot 2017-10-02 at 17 28 37](https://user-images.githubusercontent.com/6809559/31085434-63f21512-a797-11e7-8306-7e3ec5b278e7.png)

Line 3 is not visible completly. 

Thanks a lot
Pavol

**Comment by franklinyu** [comment] 2017-10-02 15:54
Duplicate of #742.

**Closed by franklinyu** 2017-10-02 15:54 UTC
