### ISSUE TITLE
MacDown 0.7.2d137 update error

### ISSUE THREAD

**Issue by briantully** [MacDownApp/macdown#1055] opened 2019-03-08 16:49 UTC
I was excited that MacDown told me a new version was available to install.

> MacDown 0.7.2d137 is now available--you have 0.7.1. Would you like to download it now?

However when I click on "Install Update" I get the following error:

> Update Error!
> An error occurred while extracting the archive. Please try again later.
 
Any idea why I can't install the update?

**Comment by FranklinYu** [comment] 2019-03-08 17:20
Duplicate of #900

**Closed by FranklinYu** 2019-03-08 17:20 UTC
