### ISSUE TITLE
Preference Markdown not visible (v 0.7.2)

### ISSUE THREAD

**Issue by chaosmonster** [MacDownApp/macdown#1132] opened 2019-12-26 09:03 UTC
The markdown pane in the preferences is not visible.
I am using version 0.7.2 (1008)

<img width="402" alt="Screenshot 2019-12-26 at 10 03 17 AM" src="https://user-images.githubusercontent.com/22507644/71468641-fa071f00-27c6-11ea-8b2c-b6a28878b9c9.png">

**Comment by iangithubusername** [comment] 2019-12-28 11:38
Looks like constraint problems.

```
error	03:35:32.712763-0800	MacDown	Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x600002d5acb0 h=--& v=--& NSView:0x7ffb2bf50020.height == 0   (active)>",
    "<NSLayoutConstraint:0x600002d4be30 V:[NSButton:0x7ffb2bf1a500'Fenced code block']-(11)-|   (active, names: '|':NSView:0x7ffb2bf50020 )>",
    "<NSLayoutConstraint:0x600002d4bbb0 V:|-(25)-[NSButton:0x7ffb2bf1a270'Table']   (active, names: '|':NSView:0x7ffb2bf50020 )>",
    "<NSLayoutConstraint:0x600002d4bd90 V:[NSButton:0x7ffb2bf1a270'Table']-(NSSpace(6))-[NSButton:0x7ffb2bf1a500'Fenced code block']   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002d4bd90 V:[NSButton:0x7ffb2bf1a270'Table']-(NSSpace(6))-[NSButton:0x7ffb2bf1a500'Fenced code block']   (active)>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
error	03:35:32.713110-0800	MacDown	Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x600002d5acb0 h=--& v=--& NSView:0x7ffb2bf50020.height == 0   (active)>",
    "<NSLayoutConstraint:0x600002d4be30 V:[NSButton:0x7ffb2bf1a500'Fenced code block']-(11)-|   (active, names: '|':NSView:0x7ffb2bf50020 )>",
    "<NSLayoutConstraint:0x600002d4bbb0 V:|-(25)-[NSButton:0x7ffb2bf1a270'Table']   (active, names: '|':NSView:0x7ffb2bf50020 )>",
    "<NSLayoutConstraint:0x600002d4bde0 V:[NSButton:0x7ffb2bf1a270'Table']-(6)-[NSButton:0x7ffb2bf1a500'Fenced code block']   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002d4bde0 V:[NSButton:0x7ffb2bf1a270'Table']-(6)-[NSButton:0x7ffb2bf1a500'Fenced code block']   (active)>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
error	03:35:32.713582-0800	MacDown	Unable to simultaneously satisfy constraints:
(
    "<NSLayoutConstraint:0x600002d4b480 V:[NSButton:0x7ffb2bf954e0'Autolink']-(6)-[NSButton:0x7ffb2bf50be0'Footnote']   (active)>",
    "<NSLayoutConstraint:0x600002d4b250 V:[NSButton:0x7ffb2bf94fc0'Superscript']-(6)-[NSButton:0x7ffb2bf954e0'Autolink']   (active)>",
    "<NSLayoutConstraint:0x600002d49fe0 V:[NSButton:0x7ffb2bf95250'Highlight']-(6)-[NSButton:0x7ffb2bf94fc0'Superscript']   (active)>",
    "<NSLayoutConstraint:0x600002d49590 V:[NSButton:0x7ffb2bf156d0'Quote']-(6)-[NSButton:0x7ffb2bf95250'Highlight']   (active)>",
    "<NSLayoutConstraint:0x600002d4a1c0 V:[NSButton:0x7ffb2bf6d1b0'Underline']-(6)-[NSButton:0x7ffb2bf156d0'Quote']   (active)>",
    "<NSLayoutConstraint:0x600002d4a710 V:[NSButton:0x7ffb2bf178f0'Strikethrough']-(6)-[NSButton:0x7ffb2bf6d1b0'Underline']   (active)>",
    "<NSLayoutConstraint:0x600002d4a580 V:[NSButton:0x7ffb2bf4f760'Intra-word emphasis']-(6)-[NSButton:0x7ffb2bf178f0'Strikethrough']   (active)>",
    "<NSLayoutConstraint:0x600002d4b340 V:[NSButton:0x7ffb2bf50be0'Footnote']-(11)-|   (active, names: '|':NSView:0x7ffb2bf70080 )>",
    "<NSLayoutConstraint:0x600002d4aa80 V:|-(25)-[NSButton:0x7ffb2bf4f760'Intra-word emphasis']   (active, names: '|':NSView:0x7ffb2bf70080 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x600002d59b30 h=--& v=--& NSView:0x7ffb2bf70080.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002d4b480 V:[NSButton:0x7ffb2bf954e0'Autolink']-(6)-[NSButton:0x7ffb2bf50be0'Footnote']   (active)>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
error	03:35:32.714147-0800	MacDown	Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x600002d55770 h=--& v=--& NSView:0x7ffb2bf18e80.height == 0   (active)>",
    "<NSLayoutConstraint:0x600002d4aad0 V:|-(25)-[NSButton:0x7ffb2bf5f120'Smartypants']   (active, names: '|':NSView:0x7ffb2bf18e80 )>",
    "<NSLayoutConstraint:0x600002d4b660 V:[NSButton:0x7ffb2bf5f120'Smartypants']-(11)-|   (active, names: '|':NSView:0x7ffb2bf18e80 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002d4b660 V:[NSButton:0x7ffb2bf5f120'Smartypants']-(11)-|   (active, names: '|':NSView:0x7ffb2bf18e80 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
```
I'm guessing the `NSAutoresizingMaskLayoutConstraint`s are unexpected and `translatesAutoresizingMaskIntoConstraints` is on by mistake somewhere.

**Comment by FranklinYu** [comment] 2019-12-29 00:43
Duplicate of #1103

**Closed** 2020-01-03 09:32 UTC
