### ISSUE TITLE
Feature - Add a file tree view/open folder option

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [MacDownApp/macdown#772] opened 2017-03-20 19:05 UTC
I'm writing some markdown docs and for me is a bit akward have to open every file one by one.

This the best MarkDown editor that I have worked with so far. Thank you for your awesome work!

**Comment by franklinyu** [comment] 2017-03-21 00:42
Please reopen if it isn't a duplicate of #141.

**Closed by franklinyu** 2017-03-21 00:42 UTC
Labels: duplicate
