### ISSUE TITLE
0.7.2 app "damanged" cannot run

### ISSUE THREAD

**Issue by ot-tony-archer** [MacDownApp/macdown#1115] opened 2019-11-29 15:55 UTC
When I download from the site or when I install from homebrew I get the following popup after running the app:

`"MacDown" is damaged and can't be ipened. You should move it to the Trash.`

How to I fix this?  I love MacDown and need it badly :)

**Comment by ot-tony-archer** [comment] 2019-11-29 15:59
Follow up:  Running this resolved it:

`xattr -cr /Applications/MacDown.app`

> -c clears attributes and -r does so recursively

**Comment by FranklinYu** [comment] 2019-11-29 23:15
Duplicate of #1106

**Closed by FranklinYu** 2019-11-29 23:15 UTC
