### ISSUE TITLE
Exporting to html from command line

### ISSUE THREAD

**Issue by jaimejim** [MacDownApp/macdown#780] opened 2017-03-29 16:10 UTC
Just like we can open files from the terminal with:

`macdown file.md`

It'd be incredibly useful to be able to export to html with base config settings:

`macdown file.md -o file.html`

**Comment by franklinyu** [comment] 2017-04-01 01:02
Please reopen if it's not duplicate of #202.

**Closed by franklinyu** 2017-04-01 01:02 UTC
