### ISSUE TITLE
Xcode Like Code Folding

### ISSUE THREAD

**Issue by Big-Pi** [MacDownApp/macdown#553] opened 2016-02-06 14:57 UTC
When i'm writting longer MarkDown, I want to fold part of the text , hope this feature will be added ;

**Comment by lucasderraugh** [comment] 2016-03-07 09:38
What would the expected behavior be in this case. Just that it hides what you've written, or also hides the preview?

**Comment by Big-Pi** [comment] 2016-03-07 10:12
Both ,so that i can : write some - fold it - then focus on other parts

**Comment by yoiang** [comment] 2017-05-08 20:33
is this a duplicate of #500?

**Comment by franklinyu** [comment] 2017-05-09 04:52
@yoiang Great, thank you! I assume that this is a duplicate of #500. Closing this until @Big-Pi tells otherwise.

**Closed by franklinyu** 2017-05-09 04:52 UTC
Labels: enhancement
