### ISSUE TITLE
Cursor should change to light cursor when using dark background themes

### ISSUE THREAD

**Issue by andrewsofie** [MacDownApp/macdown#859] opened 2017-09-30 21:46 UTC
Currently, uses dark text cursor which is very difficult to see on the themes that are dark

**Comment by franklinyu** [comment] 2017-10-03 04:21
Do you mean UI theme (for the entire application) or theme for the rendered webpage preview?

**Comment by franklinyu** [comment] 2017-10-03 23:47
Duplicate of #833.

**Closed by franklinyu** 2017-10-03 23:47 UTC
